---
sidebar: sidebar 
permalink: alerts-faq.html 
keywords: alerts faq, alerts frequently asked questions, bluexp, bluexp alert 
summary: 이 BlueXP  경고 FAQ는 질문에 대한 빠른 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= BlueXP  경고에 대한 FAQ(자주 묻는 질문
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== BlueXP  알림에 액세스합니다

* BlueXP  경고 URL은 무엇입니까? * URL의 경우 브라우저에 다음을 입력하여 BlueXP  콘솔에 액세스합니다. https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/"^]

* BlueXP  알림을 사용하려면 라이센스가 필요합니까? *

BlueXP  알림 서비스에는 NetApp ONTAP 9 .10 이상의 라이센스가 필요합니다. BlueXP  디지털 지갑에 라이센스를 입력할 필요가 없습니다.

이 서비스에 대한 평가판 라이센스가 필요하지 않습니다.

* BlueXP  알림을 어떻게 활성화합니까? * BlueXP  알림은 활성화할 필요가 없습니다. 경고 옵션은 BlueXP  왼쪽 탐색에서 자동으로 활성화됩니다.

BlueXP  커넥터를 사용할 때 서비스에 적합한 기능이 포함되어 있습니다.

** BlueXP  알림은 표준, 제한 및 개인 모드에서 사용할 수 있습니까?** 이 서비스는 BlueXP  표준(공개)으로만 구축할 수 있습니다.

모든 BlueXP  서비스에서 이러한 모드에 대한 설명은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP 배포 모드"^].

** 액세스 권한은 어떻게 처리됩니까?** BlueXP  조직 관리자만 BlueXP  경고 서비스를 시작하고 워크로드를 검색할 수 있습니다(리소스 사용을 커밋하는 작업이 포함되므로).

로그인한 사용자에게는 해당 BlueXP  조직에서 클러스터 리소스에 대한 액세스 권한에 따라 알림이 표시됩니다.

https://docs.netapp.com/us-en/bluexp-setup-admin/concept-netapp-accounts.html["BlueXP  조직에 대해 알아보십시오"]..



== 알림을 봅니다

** 알림을 받기 전에 얼마나 기다려야 합니까?**

초기 검색은 최대 15분, 초기 검색은 최대 5분 동안 기다립니다. 경고마다 다릅니다.

**BlueXP  커넥터 없이 직접 모드를 사용하는 ONTAP에 대한 경고가 표시되지 않는 이유는 무엇입니까?*

BlueXP  경고는 온프레미스 표준 BlueXP  커넥터를 사용해야만 사용할 수 있습니다. 직접 모드를 사용하면 클러스터를 모니터링하지 않으며 경고가 표시되지 않습니다.

** 경고 목록 페이지에서 일부 경고가 사라지는 이유는 무엇입니까?**

경고 기능은 일부 경고를 활성 상태로 유지하고 카운터 조건이 충족되거나 기간에 도달한 후에 닫습니다. 경고마다 다릅니다.

모든 경고를 보려면 상태 열 필터를 선택하고 닫힘 옵션을 선택합니다.



== 정보 표시

** 어떤 장치 해상도가 가장 좋습니까?** BlueXP  알림에 권장되는 장치 해상도는 1920x1080 이상입니다.

** 어떤 브라우저를 사용해야 합니까?** 모든 최신 브라우저가 작동합니다.
